main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('/education', views.educationpage, name='educationpage'),
    path('/family', views.familypage, name='familypage'),
    path('/interests', views.interestspage, name='interestspage'),
    path('/contacts', views.contactpage, name='contactpage'),
]

story4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render


def homepage(request):
    return render(request, 'main/homepage.html')

def educationpage(request) :
    return render(request, 'main/educationpage.html')

def familypage(request) :
    return render(request, 'main/familypage.html')

def interestspage(request) :
    return render(request, 'main/interestspage.html')

def contactpage(request) :
    return render(request, 'main/contactpage.html')

main/templates/main/contactpage.html
{% extends 'base.html' %}

{% block content %}
    <section class="contacts">
        <div class="container fluid-padding">
            <div class="row text-center padding">
                <div class="col-12">
                    <h1>Contact Me</h1>
                </div>
                <div class="col-12 social padding">
                    <a href = "https://instagram.com/aureliaasbr" title="go to aurel's instagram" target="_blank"><img src="static/img/instagram1.png"></a>
                    <a href = "https://www.linkedin.com/in/khalishah-aurelia-asbran-54b881193/" title="go to aurel's linkedin" target="_blank"><img src="static/img/linkedin1.png"></a>
                </div>
            </div>
        </div>
    </section>

    <footer>
        <div class="container-fluid padding">
            <div class="row text-center">
                <div class="col-md-12">
                    <hr class="light">
                    <h5>More Contacts</h5>
                    <hr class="light">
                    <p>+62878-8849-4549</p>
                    <p>aureliaasbran@gmail.com</p>
                    <p>line : aureliaasbrannn</p>
                </div>
            </div>
        </div>
    </footer>
{% endblock %}

main/templates/main/educationpage.html
{% extends 'base.html' %}}

{% block content %}
    <section class="education">
        <div class="container fluid-padding">
            <div class="education history text-center">
                <div class="col-12">
                    <h1>Education History</h1>
                </div>
            </div>
        </div>
    </section>

    <section class="education-logos">
        <div class="container fluid-padding">
            <div class="row text-center padding">
                <div class="col-xs-12 col-sm-6 col-md-4">
                    <img src="static/img/bangor-logo.png">
                    <h3>SMPN 2 Depok</h3>
                    <p>2014 - 2016</p>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-4">
                    <img src="static/img/smansa-logo.png">
                    <h3>SMAN 1 Depok</h3>
                    <p>2016 - 2019</p>
                </div>
                <div class="col-sm-12 col-md-4">
                    <img src="static/img/ui-logo.png">
                    <h3>Universitas Indonesia</h3>
                    <p>2019 - Present</p>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

main/templates/main/familypage.html
{% extends 'base.html' %}

{% block content %}
    <section class="family">
        <div class="container fluid-padding">
            <div class="row padding">
                <div class="col-md-12 col-lg-6">
                    <h1>My Family &#10084;</h1>
                    <p>This is a picture of me and both of my sisters. The one that is wearing a hijab is called Khiara, and the one
                        that has her hair down is called Syafa.
                    </p>
                    <p>An interesting fact about the three of us is that we were all born on the same date, at the same hospital,
                        and with the same doctor helping our mom deliver us! That means we all have the same birthday, which is the 3rd
                        of April. I think that's pretty interesting.
                    </p> 
                </div>
                <div class="col-lg-6">
                    <img src="static/img/mySisters.jpg" class="img-fluid">
                </div>
            </div>
        </div>
    </section>
{% endblock %}

main/templates/main/homepage.html
{% extends 'base.html' %}

{% block content %}
    <section class="home">
        <div class="home-text">
            <h1>Hello, i'm Aurel!</h1>
            <p>I am an Undergraduate Information Systems Student
                at University of Indonesia.</p>
        </div>
        <div class="my-photo">
            <img src="static/img/aurel.png">
        </div>
    </section>
{% endblock %}

main/templates/main/interestspage.html
{% extends 'base.html' %}

{% block content %}
    <section class="interests">
        <div class="container fluid-padding">
            <div class="interests text-center">
                <div class="col-12">
                    <h1>Interests and Hobbies</h1>
                </div>
            </div>
        </div>
    </section>

    <section class="interests-photos">
        <div class="container fluid-padding">
            <div class="row text-center padding">
                <div class="col-xs-12 col-sm-6 col-md-4">
                    <img src="static/img/cats.jpg">
                    <h3>cats</h3>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-4">
                    <img src="static/img/pizza.jpg">
                    <h3>food</h3>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-4">
                    <img src="static/img/movies.jpg">
                    <h3>movies</h3>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-6">
                    <img src="static/img/bts.jpg">
                    <h3>bts</h3>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-6">
                    <img src="static/img/music.jpg">
                    <h3>music</h3>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link href="https://fonts.googleapis.com/css2?family=Esteban&family=Montserrat:wght@700&family=Varela+Round&display=swap" rel="stylesheet">
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  <title>Story 4</title>
</head>

<body>
      <!--Navigation-->
      <nav class="navbar navbar-expand-md navbar-light bg-light sticky-top">
        <div class=container-fluid>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse" id=navbarResponsive>
            <ul class="navbar-nav ml-auto">
                <li class="navbar-item">
                    <a class="nav-link" href="{% url 'main:homepage' %}">home</a>
                </li>
                <li class="navbar-item">
                    <a class="nav-link" href="{% url 'main:educationpage' %}">education</a>
                </li>
                <li class="navbar-item">
                    <a class="nav-link" href="{% url 'main:familypage' %}">family</a>
                </li>
                <li class="navbar-item">
                    <a class="nav-link" href="{% url 'main:interestspage' %}">interests</a>
                </li>
                <li class="navbar-item">
                    <a class="nav-link" href="{% url 'main:contactpage' %}">contact</a>
                </li>
                <li class="navbar-item">
                    <a class="nav-link" href="https://thisisaurel.herokuapp.com/" target="_blank">story1</a>
                </li>
            </ul>
        </div>
    </nav>
  {% block content %}
  {% endblock content %}
</body>
</html>